
import type { Generator } from './types';

export const GENERATORS_DATA: Generator[] = [
  {
    id: 'gen-62',
    name: 'Compact Powerhouse 62',
    kva: '62',
    imageUrl: 'https://i.ibb.co/6yVw4z9/image.png',
    description: 'Ideal for small-scale events, residential backup, and small construction sites. Quiet, efficient, and easy to transport.',
    power: '49.6 kW',
    output: '240V, Single-Phase',
    fuelType: 'Diesel',
    pricePerAdditionalHour: 850,
  },
  {
    id: 'gen-125',
    name: 'Mid-Range Reliable 125',
    kva: '125',
    imageUrl: 'https://i.ibb.co/rfnf20M/image.png',
    description: 'Our most popular model. Perfect for medium-sized commercial needs, larger events, and extensive construction projects.',
    power: '100 kW',
    output: '415V, Three-Phase',
    fuelType: 'Diesel',
    pricePerAdditionalHour: 850,
  },
  {
    id: 'gen-180',
    name: 'Commercial Pro 180',
    kva: '180',
    imageUrl: 'https://i.ibb.co/zJtBHT7/image.png',
    description: 'A robust solution for industrial applications, large-scale events, and critical infrastructure backup. Built for continuous operation.',
    power: '144 kW',
    output: '415V, Three-Phase',
    fuelType: 'Diesel',
    pricePerAdditionalHour: 850,
  },
  {
    id: 'gen-250',
    name: 'Industrial Force 250',
    kva: '250',
    imageUrl: 'https://i.ibb.co/vVRSmR3/image.png',
    description: 'Designed for heavy-duty industrial use, manufacturing plants, and large data centers. Provides substantial, reliable power.',
    power: '200 kW',
    output: '415V, Three-Phase',
    fuelType: 'Diesel',
    pricePerAdditionalHour: 850,
  },
  {
    id: 'gen-320',
    name: 'Power Titan 320',
    kva: '320',
    imageUrl: 'https://i.ibb.co/Xz9Zk6Q/image.png',
    description: 'For major power requirements such as large factories, hospitals, or entire building complexes. Ensures uninterrupted power supply.',
    power: '256 kW',
    output: '415V, Three-Phase',
    fuelType: 'Diesel',
    pricePerAdditionalHour: 850,
  },
  {
    id: 'gen-380',
    name: 'Mega Power 380',
    kva: '380',
    imageUrl: 'https://i.ibb.co/rGtLp7R/image.png',
    description: 'An extreme power solution for the most demanding scenarios, including large-scale industrial operations and emergency power.',
    power: '304 kW',
    output: '415V, Three-Phase',
    fuelType: 'Diesel',
    pricePerAdditionalHour: 850,
  },
  {
    id: 'gen-500',
    name: 'Goliath 500',
    kva: '500',
    imageUrl: 'https://i.ibb.co/yQJkH7M/image.png',
    description: 'The ultimate power solution for metropolitan-level needs, massive industrial sites, and critical utility backup. Unmatched performance.',
    power: '400 kW',
    output: '415V, Three-Phase',
    fuelType: 'Diesel',
    pricePerAdditionalHour: 850,
  },
];
